spring:
  datasource:
    url: jdbc:mysql://47.107.178.133:3306/trade_manage_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Devin@123456
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true